spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    access-key:
    secret-key:
    oss:
      endpotint: oss-cn-guangzhou.aliyuncs.com
      bucket: spriitmall
  application:
    name: spiritmall-third-party

server:
  port: 30000
alibaba:









